version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 10
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 3000
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 200
  method-lines:
    config:
      threshold: 200
  nested-control-flow:
    config:
      threshold: 10
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 90
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.